blank_issues_enabled: false
contact_links:
  - name: Join the Discord for support with ModMail!
    url: https://discord.gg/jQJnav2jPu
    about: If you're looking for support, it's easier for the ModMail development team to support you through our Discord server. If you're not looking for support, please check for a duplicate of your issue before opening a report. Thanks!
