name: Build Only

on:
  push:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4

        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Project
        run: ./gradlew build --stacktrace

      - name: Extract Current Branch name
        shell: bash

        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
        id: ref

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4

        with:
          name: build-artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs/*[0-9].jar
